{"uuid": "ca0b43a4-437d-4899-90ef-099c42a8a1fc", "children": ["1005a6c8-409f-4253-aaea-e870f408dc32"], "befores": [{"name": "appium_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /appium/device/pixel_ratio' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /appium/device/pixel_ratio' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\n    at UIA2Proxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\n", "trace": "  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Python_Demo\\test_cases\\conftest.py\", line 30, in appium_driver\n    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 273, in __init__\n    super().__init__(\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 364, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1638784655930, "stop": 1638784664894}], "start": 1638784655930, "stop": 1638784665052}